version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:8.0.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"   # external client access
      - "9093:9093"   # inter-broker
      - "9094:9094"   # controller
    environment:
      # Unique cluster ID and node ID
      CLUSTER_ID: MqUdYjvqR4dlbL6zB2Dq8Q
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Multi-listener config
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,CLIENT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,CLIENT://kafka:9092,CONTROLLER://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Replication settings for single broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

      # Allow topic auto creation off for consistency
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"



  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    hostname: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=localCluster
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
    depends_on:
      - kafka
    restart: unless-stopped

  device-gateway-service:
    build: .
    container_name: device-gateway-service
    depends_on:
      - kafka
      - redis
    ports:
      - "8081:8081"
      - "5023:5023"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_GROUP_ID: device-gateway-consumer-group
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      TCP_PORT: 5023

      DEVICE_GATEWAY_SESSION_IDLE_TIMEOUT: 600
      DEVICE_GATEWAY_SESSION_CLEANUP_INTERVAL: 60
    restart: unless-stopped

volumes:
  kafka-data: